version: '3.8'

services:
  db:
    image: postgres:15
    container_name: task_db
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: task_backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    env_file:
      - .env

  frontend:
    build: ./frontend
    container_name: task_frontend
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  pgdata:
